apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-jay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-jay
  template:
    metadata:
      labels:
        app: my-app-jay
      annotations:
        os.arch: alpine
        os.version: "3.20"
        middleware.name: nodejs
        middleware.version: "18.17.1"
    spec:
      containers:
      - name:  my-app-jay-container
        image: nginx
